version: '3.8'

services:
  app:
    build: .
    volumes:
      - .:/app
    command: /start.sh
    entrypoint: /entrypoint.sh
    restart: on-failure
    env_file: .env
    stdin_open: true
    tty: true
    ports:
      - "8000:8000"