# Generated by Django 2.2.9 on 2021-01-16 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_auto_20210116_0644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='stock_type',
            field=models.CharField(choices=[('daily', 'DAILY'), ('weekly', 'WEEKLY'), ('monthly', 'MONTHLY')], default='monthly', max_length=50),
        ),
    ]
