# Generated by Django 2.2.9 on 2021-01-24 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_auto_20210124_1040'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockproduct',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='stockproduct',
            unique_together={('stock', 'product')},
        ),
    ]
