# Generated by Django 2.1.3 on 2019-01-27 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='tags',
        ),
        migrations.AddField(
            model_name='product',
            name='ttags',
            field=models.ManyToManyField(related_name='articles', to='products.Tag'),
        ),
    ]
