# Generated by Django 2.1.4 on 2018-12-24 09:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20181224_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default=uuid.uuid4, max_length=100, unique=True),
        ),
    ]
