# Generated by Django 2.1.4 on 2018-12-26 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20181226_1642'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='owner',
            new_name='owner_id',
        ),
    ]
