# Generated by Django 2.1.4 on 2018-12-26 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20181226_1644'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='owner_id',
            new_name='owner',
        ),
    ]
