# Generated by Django 2.2.9 on 2021-01-16 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_store_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='active',
        ),
    ]
