# Generated by Django 2.1.4 on 2018-12-24 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='owner',
        ),
    ]
